server:
  port: ${PORT:8081}

spring:
  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT:localhost:5432}/auth_db
    username: ${AUTH_DB_USERNAME:auth_user}
    password: ${AUTH_DB_PASSWORD:auth_password}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

# Service endpoints
services:
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service:8084}

# Disable API docs in production
springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.roomiematcher: ${LOG_LEVEL:INFO}
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 