server:
  port: 8084
  servlet:
    context-path: /api/v1

spring:
  application:
    name: notification-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/roomie_notification}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        generate_statistics: false
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your_email@gmail.com}
    password: ${MAIL_PASSWORD:your_app_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    cache: true
    prefix: classpath:/templates/email/
    suffix: .html
    mode: HTML

# AWS SES Configuration (used only when notification.provider=aws-ses)
aws:
  ses:
    region: ${AWS_SES_REGION:us-east-1}
    from-email: ${AWS_SES_FROM_EMAIL:no-reply@roomiematcher.com}
    access-key: ${AWS_SES_ACCESS_KEY:}
    secret-key: ${AWS_SES_SECRET_KEY:}

# Email Provider Configuration
notification:
  provider: ${NOTIFICATION_PROVIDER:aws-ses}

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging
logging:
  level:
    root: WARN
    com.roomiematcher: INFO
    org.springframework: WARN
  file:
    max-size: 10MB
    max-history: 3

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key_here}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized 