version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: roomiematcher-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - roomiematcher-network

  api-gateway:
    build: ./api-gateway-service
    container_name: roomiematcher-api-gateway
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081/api/v1
      - PROFILE_SERVICE_URL=http://profile-service:8082/api/v1
      - MATCH_SERVICE_URL=http://match-service:8083/api/v1
      - NOTIFICATION_SERVICE_URL=http://notification-service:8084/api/v1
      - JWT_SECRET=your_jwt_secret_key_here
    depends_on:
      - auth-service
      - profile-service
      - match-service
      - notification-service
    networks:
      - roomiematcher-network

  auth-service:
    build: ./auth-service
    container_name: roomiematcher-auth-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - NOTIFICATION_SERVICE_URL=http://notification-service:8084/api/v1
      - JWT_SECRET=your_jwt_secret_key_here
    depends_on:
      - postgres
    networks:
      - roomiematcher-network

  profile-service:
    build: ./profile-service
    container_name: roomiematcher-profile-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/profile_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=your_jwt_secret_key_here
    depends_on:
      - postgres
    networks:
      - roomiematcher-network

  match-service:
    build: ./match-service
    container_name: roomiematcher-match-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/match_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - PROFILE_SERVICE_URL=http://profile-service:8082/api/v1
      - JWT_SECRET=your_jwt_secret_key_here
    depends_on:
      - postgres
      - profile-service
    networks:
      - roomiematcher-network

  notification-service:
    build: ./notification-service
    container_name: roomiematcher-notification-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/notification_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=your_email@gmail.com
      - MAIL_PASSWORD=your_app_password
      - JWT_SECRET=your_jwt_secret_key_here
      - AWS_SES_ENABLED=false
    depends_on:
      - postgres
    networks:
      - roomiematcher-network

networks:
  roomiematcher-network:
    driver: bridge

volumes:
  postgres-data:
