AWSTemplateFormatVersion: '2010-09-09'
Description: 'RoomieMatcher - ECS Task Definitions'

Parameters:
  EnvironmentName:
    Description: Environment name (dev, staging, prod)
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
  
  AuthServiceImage:
    Description: Auth Service Docker image URI
    Type: String
  
  ProfileServiceImage:
    Description: Profile Service Docker image URI
    Type: String
  
  MatchServiceImage:
    Description: Match Service Docker image URI
    Type: String
  
  NotificationServiceImage:
    Description: Notification Service Docker image URI
    Type: String
  
  ApiGatewayImage:
    Description: API Gateway Docker image URI
    Type: String
  
  JwtSecret:
    Description: Secret for JWT token signing
    Type: String
    NoEcho: true
  
  DBMasterUsername:
    Description: Database master username
    Type: String
    Default: postgres
    NoEcho: false
  
  DBMasterPassword:
    Description: Database master password
    Type: String
    NoEcho: true
  
  AwsSesAccessKey:
    Description: AWS SES Access Key
    Type: String
    NoEcho: true
  
  AwsSesSecretKey:
    Description: AWS SES Secret Key
    Type: String
    NoEcho: true
  
  AwsSesRegion:
    Description: AWS SES Region
    Type: String
    Default: us-east-1
  
  AwsSesFromEmail:
    Description: AWS SES From Email
    Type: String
    Default: no-reply@roomiematcher.com

Resources:
  # Task Definitions
  AuthServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${EnvironmentName}-auth-service
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: 
        Fn::ImportValue: !Sub ${EnvironmentName}-ECSTaskExecutionRole
      TaskRoleArn: 
        Fn::ImportValue: !Sub ${EnvironmentName}-ECSTaskRole
      ContainerDefinitions:
        - Name: auth-service
          Image: !Ref AuthServiceImage
          Essential: true
          PortMappings:
            - ContainerPort: 8081
              HostPort: 8081
              Protocol: tcp
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: prod
            - Name: SPRING_DATASOURCE_URL
              Value: !Sub jdbc:postgresql://${AuthDatabaseEndpoint}:${DatabasePort}/roomie_auth
            - Name: SPRING_DATASOURCE_USERNAME
              Value: !Ref DBMasterUsername
            - Name: SPRING_DATASOURCE_PASSWORD
              Value: !Ref DBMasterPassword
            - Name: JWT_SECRET
              Value: !Ref JwtSecret
            - Name: NOTIFICATION_SERVICE_URL
              Value: !Sub http://notification-service.${EnvironmentName}.roomie-matcher.local:8084/api/v1
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: 
                Fn::ImportValue: !Sub ${EnvironmentName}-LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: auth-service
  
  ProfileServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${EnvironmentName}-profile-service
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: 
        Fn::ImportValue: !Sub ${EnvironmentName}-ECSTaskExecutionRole
      TaskRoleArn: 
        Fn::ImportValue: !Sub ${EnvironmentName}-ECSTaskRole
      ContainerDefinitions:
        - Name: profile-service
          Image: !Ref ProfileServiceImage
          Essential: true
          PortMappings:
            - ContainerPort: 8082
              HostPort: 8082
              Protocol: tcp
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: prod
            - Name: SPRING_DATASOURCE_URL
              Value: !Sub jdbc:postgresql://${ProfileDatabaseEndpoint}:${DatabasePort}/roomie_profile
            - Name: SPRING_DATASOURCE_USERNAME
              Value: !Ref DBMasterUsername
            - Name: SPRING_DATASOURCE_PASSWORD
              Value: !Ref DBMasterPassword
            - Name: JWT_SECRET
              Value: !Ref JwtSecret
            - Name: AUTH_SERVICE_URL
              Value: !Sub http://auth-service.${EnvironmentName}.roomie-matcher.local:8081/api/v1
            - Name: NOTIFICATION_SERVICE_URL
              Value: !Sub http://notification-service.${EnvironmentName}.roomie-matcher.local:8084/api/v1
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: 
                Fn::ImportValue: !Sub ${EnvironmentName}-LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: profile-service
  
  MatchServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${EnvironmentName}-match-service
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: 
        Fn::ImportValue: !Sub ${EnvironmentName}-ECSTaskExecutionRole
      TaskRoleArn: 
        Fn::ImportValue: !Sub ${EnvironmentName}-ECSTaskRole
      ContainerDefinitions:
        - Name: match-service
          Image: !Ref MatchServiceImage
          Essential: true
          PortMappings:
            - ContainerPort: 8083
              HostPort: 8083
              Protocol: tcp
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: prod
            - Name: SPRING_DATASOURCE_URL
              Value: !Sub jdbc:postgresql://${MatchDatabaseEndpoint}:${DatabasePort}/roomie_match
            - Name: SPRING_DATASOURCE_USERNAME
              Value: !Ref DBMasterUsername
            - Name: SPRING_DATASOURCE_PASSWORD
              Value: !Ref DBMasterPassword
            - Name: JWT_SECRET
              Value: !Ref JwtSecret
            - Name: PROFILE_SERVICE_URL
              Value: !Sub http://profile-service.${EnvironmentName}.roomie-matcher.local:8082/api/v1
            - Name: NOTIFICATION_SERVICE_URL
              Value: !Sub http://notification-service.${EnvironmentName}.roomie-matcher.local:8084/api/v1
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: 
                Fn::ImportValue: !Sub ${EnvironmentName}-LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: match-service
  
  NotificationServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${EnvironmentName}-notification-service
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: 
        Fn::ImportValue: !Sub ${EnvironmentName}-ECSTaskExecutionRole
      TaskRoleArn: 
        Fn::ImportValue: !Sub ${EnvironmentName}-ECSTaskRole
      ContainerDefinitions:
        - Name: notification-service
          Image: !Ref NotificationServiceImage
          Essential: true
          PortMappings:
            - ContainerPort: 8084
              HostPort: 8084
              Protocol: tcp
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: prod
            - Name: NOTIFICATION_PROVIDER
              Value: aws-ses
            - Name: AWS_SES_ACCESS_KEY
              Value: !Ref AwsSesAccessKey
            - Name: AWS_SES_SECRET_KEY
              Value: !Ref AwsSesSecretKey
            - Name: AWS_SES_REGION
              Value: !Ref AwsSesRegion
            - Name: AWS_SES_FROM_EMAIL
              Value: !Ref AwsSesFromEmail
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: 
                Fn::ImportValue: !Sub ${EnvironmentName}-LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: notification-service
  
  ApiGatewayTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${EnvironmentName}-api-gateway
      Cpu: '512'
      Memory: '1024'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: 
        Fn::ImportValue: !Sub ${EnvironmentName}-ECSTaskExecutionRole
      TaskRoleArn: 
        Fn::ImportValue: !Sub ${EnvironmentName}-ECSTaskRole
      ContainerDefinitions:
        - Name: api-gateway
          Image: !Ref ApiGatewayImage
          Essential: true
          PortMappings:
            - ContainerPort: 8080
              HostPort: 8080
              Protocol: tcp
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: prod
            - Name: JWT_SECRET
              Value: !Ref JwtSecret
            - Name: AUTH_SERVICE_URL
              Value: !Sub http://auth-service.${EnvironmentName}.roomie-matcher.local:8081/api/v1
            - Name: PROFILE_SERVICE_URL
              Value: !Sub http://profile-service.${EnvironmentName}.roomie-matcher.local:8082/api/v1
            - Name: MATCH_SERVICE_URL
              Value: !Sub http://match-service.${EnvironmentName}.roomie-matcher.local:8083/api/v1
            - Name: NOTIFICATION_SERVICE_URL
              Value: !Sub http://notification-service.${EnvironmentName}.roomie-matcher.local:8084/api/v1
            - Name: ALLOWED_ORIGINS
              Value: !If [IsProd, 'https://roomiematcher.com', 'http://localhost:3000']
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: 
                Fn::ImportValue: !Sub ${EnvironmentName}-LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: api-gateway

Conditions:
  IsProd: !Equals [!Ref EnvironmentName, 'prod']

Outputs:
  AuthServiceTaskDefinition:
    Description: Auth Service Task Definition ARN
    Value: !Ref AuthServiceTaskDefinition
    Export:
      Name: !Sub ${EnvironmentName}-AuthServiceTaskDefinition
  
  ProfileServiceTaskDefinition:
    Description: Profile Service Task Definition ARN
    Value: !Ref ProfileServiceTaskDefinition
    Export:
      Name: !Sub ${EnvironmentName}-ProfileServiceTaskDefinition
  
  MatchServiceTaskDefinition:
    Description: Match Service Task Definition ARN
    Value: !Ref MatchServiceTaskDefinition
    Export:
      Name: !Sub ${EnvironmentName}-MatchServiceTaskDefinition
  
  NotificationServiceTaskDefinition:
    Description: Notification Service Task Definition ARN
    Value: !Ref NotificationServiceTaskDefinition
    Export:
      Name: !Sub ${EnvironmentName}-NotificationServiceTaskDefinition
  
  ApiGatewayTaskDefinition:
    Description: API Gateway Task Definition ARN
    Value: !Ref ApiGatewayTaskDefinition
    Export:
      Name: !Sub ${EnvironmentName}-ApiGatewayTaskDefinition 