server:
  port: 8082
  servlet:
    context-path: /api/profiles

spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:postgresql://localhost:5432/roomie_profile
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

# Service endpoints
services:
  auth-service:
    url: http://localhost:8081
  notification-service:
    url: http://localhost:8084

# OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method 