server:
  port: 8081
  servlet:
    context-path: /api/auth

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/roomie_auth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000  # 24 hours

# Service endpoints
services:
  notification-service:
    url: http://localhost:8084

# OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method 