spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

# AWS SES Configuration
aws:
  ses:
    access-key: ${AWS_SES_ACCESS_KEY}
    secret-key: ${AWS_SES_SECRET_KEY}
    region: ${AWS_SES_REGION}
    from-email: ${AWS_SES_FROM_EMAIL}

# Email Provider Configuration
notification:
  provider: ${NOTIFICATION_PROVIDER:aws-ses}

# Logging
logging:
  level:
    com.roomiematcher: INFO
    org.springframework.web: WARN 