server:
  port: 8084
  servlet:
    context-path: /api/v1

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# AWS SES Configuration (used only when notification.provider=aws-ses)
aws:
  ses:
    access-key: ${AWS_SES_ACCESS_KEY:}
    secret-key: ${AWS_SES_SECRET_KEY:}
    region: ${AWS_SES_REGION:us-east-1}
    from-email: ${AWS_SES_FROM_EMAIL:no-reply@yourdomain.com}

# Email Provider Configuration
notification:
  provider: standard # standard, aws-ses

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging
logging:
  level:
    com.roomiematcher: DEBUG
    org.springframework.web: INFO 