server:
  port: ${PORT:8082}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

jwt:
  secret: ${JWT_SECRET}

# Service endpoints
services:
  auth-service:
    url: ${AUTH_SERVICE_URL:http://auth-service:8081}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service:8084}

# Disable API docs in production
springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.roomiematcher: ${LOG_LEVEL:INFO}
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 