AWSTemplateFormatVersion: '2010-09-09'
Description: 'RoomieMatcher - RDS PostgreSQL Database Infrastructure'

Parameters:
  EnvironmentName:
    Description: Environment name (dev, staging, prod)
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
  
  DBInstanceClass:
    Description: Database instance class
    Type: String
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
      - db.t3.large
      - db.r5.large
  
  DBMasterUsername:
    Description: Database master username
    Type: String
    Default: postgres
    NoEcho: false
  
  DBMasterPassword:
    Description: Database master password
    Type: String
    NoEcho: true
    MinLength: 8
  
  DBAllocatedStorage:
    Description: Database allocated storage in GB
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 100
  
  DBBackupRetentionPeriod:
    Description: Database backup retention period in days
    Type: Number
    Default: 7
    MinValue: 0
    MaxValue: 35

Resources:
  # RDS Parameter Group
  RDSParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub ${EnvironmentName} RoomieMatcher PostgreSQL parameter group
      Family: postgres15
      Parameters:
        max_connections: '100'
        shared_buffers: '{DBInstanceClass}' 
        effective_cache_size: '{DBInstanceClass}'
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
  
  # RDS Subnet Group
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub ${EnvironmentName} RoomieMatcher DB subnet group
      SubnetIds:
        - Fn::ImportValue: !Sub ${EnvironmentName}-PrivateSubnet1
        - Fn::ImportValue: !Sub ${EnvironmentName}-PrivateSubnet2
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
  
  # Auth Database
  AuthDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: roomie_auth
      Engine: postgres
      EngineVersion: 15.3
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      StorageType: gp2
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterPassword
      DBParameterGroupName: !Ref RDSParameterGroup
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub ${EnvironmentName}-DatabaseSecurityGroup
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      MultiAZ: !If [IsProd, true, false]
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-auth-db
        - Key: Environment
          Value: !Ref EnvironmentName
  
  # Profile Database
  ProfileDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: roomie_profile
      Engine: postgres
      EngineVersion: 15.3
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      StorageType: gp2
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterPassword
      DBParameterGroupName: !Ref RDSParameterGroup
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub ${EnvironmentName}-DatabaseSecurityGroup
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      MultiAZ: !If [IsProd, true, false]
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-profile-db
        - Key: Environment
          Value: !Ref EnvironmentName
  
  # Match Database
  MatchDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: roomie_match
      Engine: postgres
      EngineVersion: 15.3
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      StorageType: gp2
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterPassword
      DBParameterGroupName: !Ref RDSParameterGroup
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub ${EnvironmentName}-DatabaseSecurityGroup
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      MultiAZ: !If [IsProd, true, false]
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-match-db
        - Key: Environment
          Value: !Ref EnvironmentName

Conditions:
  IsProd: !Equals [!Ref EnvironmentName, 'prod']

Outputs:
  AuthDatabaseEndpoint:
    Description: Auth Database Endpoint
    Value: !GetAtt AuthDatabase.Endpoint.Address
    Export:
      Name: !Sub ${EnvironmentName}-AuthDatabaseEndpoint
  
  ProfileDatabaseEndpoint:
    Description: Profile Database Endpoint
    Value: !GetAtt ProfileDatabase.Endpoint.Address
    Export:
      Name: !Sub ${EnvironmentName}-ProfileDatabaseEndpoint
  
  MatchDatabaseEndpoint:
    Description: Match Database Endpoint
    Value: !GetAtt MatchDatabase.Endpoint.Address
    Export:
      Name: !Sub ${EnvironmentName}-MatchDatabaseEndpoint
  
  DatabasePort:
    Description: Database Port
    Value: !GetAtt AuthDatabase.Endpoint.Port
    Export:
      Name: !Sub ${EnvironmentName}-DatabasePort 