server:
  port: ${PORT:8083}

spring:
  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT:localhost:5432}/match_db
    username: ${MATCH_DB_USERNAME:match_user}
    password: ${MATCH_DB_PASSWORD:match_password}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}

# Service endpoints for Feign clients
services:
  profile-service:
    url: ${PROFILE_SERVICE_URL:http://profile-service:8082}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service:8084}

# Disable API docs in production
springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}

# Logging
logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.roomiematcher: ${LOG_LEVEL:INFO}
    org.springframework.web: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 