spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS:https://roomiematcher.com}
            allowedMethods: "*"
            allowedHeaders: "*"

# Service URLs
services:
  auth-service:
    url: ${AUTH_SERVICE_URL}
  profile-service:
    url: ${PROFILE_SERVICE_URL}
  match-service:
    url: ${MATCH_SERVICE_URL}
  notification-service:
    url: ${NOTIFICATION_SERVICE_URL}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}

# Logging
logging:
  level:
    com.roomiematcher: INFO
    org.springframework.cloud.gateway: WARN
    org.springframework.web: WARN 