AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for RDS PostgreSQL instance for RoomieMatcher'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC where RDS will be deployed

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs for the RDS instance

  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    Description: RDS instance type
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
      - db.t4g.micro
      - db.t4g.small

  DBName:
    Type: String
    Default: postgres
    Description: Main database name

  DBUsername:
    Type: String
    Description: Master username for the RDS instance
    NoEcho: true

  DBPassword:
    Type: String
    Description: Master password for the RDS instance
    NoEcho: true

  DBAllocatedStorage:
    Type: Number
    Default: 20
    Description: Allocated storage in GB
    MinValue: 20
    MaxValue: 100

  DBBackupRetentionPeriod:
    Type: Number
    Default: 7
    Description: Number of days to retain backups
    MinValue: 0
    MaxValue: 35

  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment

Resources:
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS PostgreSQL
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0  # In production, restrict to your application security group
      Tags:
        - Key: Name
          Value: !Sub 'roomiematcher-${Environment}-db-sg'

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RoomieMatcher RDS
      SubnetIds: !Ref SubnetIds
      Tags:
        - Key: Name
          Value: !Sub 'roomiematcher-${Environment}-db-subnet-group'

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub 'roomiematcher-${Environment}-db'
      AllocatedStorage: !Ref DBAllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      Engine: postgres
      EngineVersion: '13.7'
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBName: !Ref DBName
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      MultiAZ: !If [IsProd, true, false]
      PubliclyAccessible: false
      StorageType: gp2
      StorageEncrypted: true
      DeletionProtection: !If [IsProd, true, false]
      Tags:
        - Key: Name
          Value: !Sub 'roomiematcher-${Environment}-db'
        - Key: Environment
          Value: !Ref Environment

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']

Outputs:
  RDSEndpoint:
    Description: RDS instance endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-RDSEndpoint'

  RDSPort:
    Description: RDS instance port
    Value: !GetAtt RDSInstance.Endpoint.Port
    Export:
      Name: !Sub '${AWS::StackName}-RDSPort'

  DBSecurityGroupId:
    Description: Security group ID for the RDS instance
    Value: !Ref DBSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-DBSecurityGroupId' 