name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # or your production branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: maven

      - name: Make scripts executable
        run: |
          chmod +x mvnw
          chmod +x build-and-push.sh

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build, tag, and push Docker images to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ./build-and-push.sh $ECR_REGISTRY $IMAGE_TAG
          echo "image=$ECR_REGISTRY/roomiematcher-api-gateway:$IMAGE_TAG" >> $GITHUB_OUTPUT
      
      - name: Update Dockerrun.aws.json with new image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
          MASTER_DB_USERNAME: ${{ secrets.MASTER_DB_USERNAME }}
          MASTER_DB_PASSWORD: ${{ secrets.MASTER_DB_PASSWORD }}
          AUTH_DB_USERNAME: ${{ secrets.AUTH_DB_USERNAME }}
          AUTH_DB_PASSWORD: ${{ secrets.AUTH_DB_PASSWORD }}
          PROFILE_DB_USERNAME: ${{ secrets.PROFILE_DB_USERNAME }}
          PROFILE_DB_PASSWORD: ${{ secrets.PROFILE_DB_PASSWORD }}
          MATCH_DB_USERNAME: ${{ secrets.MATCH_DB_USERNAME }}
          MATCH_DB_PASSWORD: ${{ secrets.MATCH_DB_PASSWORD }}
          NOTIFICATION_DB_USERNAME: ${{ secrets.NOTIFICATION_DB_USERNAME }}
          NOTIFICATION_DB_PASSWORD: ${{ secrets.NOTIFICATION_DB_PASSWORD }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          AWS_SES_ENABLED: ${{ secrets.AWS_SES_ENABLED }}
          AWS_SES_ACCESS_KEY: ${{ secrets.AWS_SES_ACCESS_KEY }}
          AWS_SES_SECRET_KEY: ${{ secrets.AWS_SES_SECRET_KEY }}
          AWS_SES_REGION: ${{ secrets.AWS_SES_REGION }}
          AWS_SES_FROM_EMAIL: ${{ secrets.AWS_SES_FROM_EMAIL }}
          NOTIFICATION_PROVIDER: ${{ secrets.NOTIFICATION_PROVIDER }}
        run: |
          sed -i "s|\${AWS_ACCOUNT_ID}|$AWS_ACCOUNT_ID|g" Dockerrun.aws.json
          sed -i "s|\${AWS_REGION}|$AWS_REGION|g" Dockerrun.aws.json
          sed -i "s|\${JWT_SECRET}|$JWT_SECRET|g" Dockerrun.aws.json
          sed -i "s|\${RDS_ENDPOINT}|$RDS_ENDPOINT|g" Dockerrun.aws.json
          sed -i "s|\${MASTER_DB_USERNAME}|$MASTER_DB_USERNAME|g" Dockerrun.aws.json
          sed -i "s|\${MASTER_DB_PASSWORD}|$MASTER_DB_PASSWORD|g" Dockerrun.aws.json
          sed -i "s|\${AUTH_DB_USERNAME}|$AUTH_DB_USERNAME|g" Dockerrun.aws.json
          sed -i "s|\${AUTH_DB_PASSWORD}|$AUTH_DB_PASSWORD|g" Dockerrun.aws.json
          sed -i "s|\${PROFILE_DB_USERNAME}|$PROFILE_DB_USERNAME|g" Dockerrun.aws.json
          sed -i "s|\${PROFILE_DB_PASSWORD}|$PROFILE_DB_PASSWORD|g" Dockerrun.aws.json
          sed -i "s|\${MATCH_DB_USERNAME}|$MATCH_DB_USERNAME|g" Dockerrun.aws.json
          sed -i "s|\${MATCH_DB_PASSWORD}|$MATCH_DB_PASSWORD|g" Dockerrun.aws.json
          sed -i "s|\${NOTIFICATION_DB_USERNAME}|$NOTIFICATION_DB_USERNAME|g" Dockerrun.aws.json
          sed -i "s|\${NOTIFICATION_DB_PASSWORD}|$NOTIFICATION_DB_PASSWORD|g" Dockerrun.aws.json
          sed -i "s|\${MAIL_HOST}|$MAIL_HOST|g" Dockerrun.aws.json
          sed -i "s|\${MAIL_PORT}|$MAIL_PORT|g" Dockerrun.aws.json
          sed -i "s|\${MAIL_USERNAME}|$MAIL_USERNAME|g" Dockerrun.aws.json
          sed -i "s|\${MAIL_PASSWORD}|$MAIL_PASSWORD|g" Dockerrun.aws.json
          sed -i "s|\${AWS_SES_ENABLED}|$AWS_SES_ENABLED|g" Dockerrun.aws.json
          sed -i "s|\${AWS_SES_ACCESS_KEY}|$AWS_SES_ACCESS_KEY|g" Dockerrun.aws.json
          sed -i "s|\${AWS_SES_SECRET_KEY}|$AWS_SES_SECRET_KEY|g" Dockerrun.aws.json
          sed -i "s|\${AWS_SES_REGION}|$AWS_SES_REGION|g" Dockerrun.aws.json
          sed -i "s|\${AWS_SES_FROM_EMAIL}|$AWS_SES_FROM_EMAIL|g" Dockerrun.aws.json
          sed -i "s|\${NOTIFICATION_PROVIDER}|$NOTIFICATION_PROVIDER|g" Dockerrun.aws.json
      
      - name: Generate deployment package
        run: |
          mkdir -p deploy_package
          cp -r .ebextensions deploy_package/
          cp Dockerrun.aws.json deploy_package/
          cd deploy_package && zip -r ../deploy.zip .
      
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: roomiematcher
          environment_name: roomiematcher-prod
          version_label: ${{ github.sha }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
          wait_for_environment_recovery: 300 